services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - banco-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - banco-net

  create-topic:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      sleep 10 &&
      kafka-topics --bootstrap-server kafka:9092 \
      --create --if-not-exists \
      --topic replicacion_banco \
      --replication-factor 1 \
      --partitions 1
      "
    networks:
      - banco-net

  oracle1:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle1
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
    networks:
      - banco-net

  oracle2:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle2
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PWD=oracle
    networks:
      - banco-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - banco-net

  producer:
    build: ./app/producer
    container_name: producer
    depends_on:
      - kafka
      - oracle1
      - oracle2
    networks:
      - banco-net

  consumer:
    build: ./app/consumer
    container_name: consumer
    depends_on:
      - kafka
      - mongo
    networks:
      - banco-net

  web:
    build: ./app/web
    container_name: flask-web
    ports:
      - "5000:5000"
    depends_on:
      - oracle1
    networks:
      - banco-net

networks:
  banco-net:
    driver: bridge
